### ISSUE TITLE
Option to add `--profile` or custom config file for `mongod`

### ISSUE THREAD

**Issue by arvenil** [Percona-QA/percona-qa#251]
Would be nice to be able enable profiling for mongod e.g. `--profile 1 --slowms 200` or `--profile 2`
https://www.percona.com/doc/percona-monitoring-and-management/conf-mongodb.html

Or somehow implement custom params for db instances.

**Comment by RoelVdP** [comment]
@arvenil in which tool? (filename)?

**Comment by arvenil** [comment]
https://github.com/Percona-QA/percona-qa/blob/24ea45878dc498966d4d963ae7b58c710f4ccccf/pmm-tests/pmm-framework.sh#L726 Now it's hardcoded.

**Comment by arvenil** [comment]
Looks like actually @Nailya added it recently ;)

**Comment by RoelVdP** [comment]
@arvenil ah, so it can be closed out?

**Comment by arvenil** [comment]
I think yes, thanks Roel ;)
