### ISSUE TITLE
Add test for Memory Auto Configuration for PMM

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#258]
Tracked in:
https://jira.percona.com/browse/PMM-2046

There are 2 options as I understand:
* --memory -> appending to docker run
* -e METRICS_MEMORY -> appending to docker run command as well

First container needs to be started with specified options then needs to be verified.

**Comment by ShahriyarR** [comment]
Can be tested as:

```
docker run -d    -p $PORT:80 --restart always  -e QUERIES_RETENTION=4 -e METRICS_MEMORY=1024000  --volumes-from pmm-data    --name pmm-server    perconalab/pmm-server:$VERSION
```

```
docker exec -it pmm-server cat /etc/supervisord.d/pmm.ini |grep heap
```

Check Also the promoteus is using the heap:

```
$ ps aux |grep promet |grep heap
```

**Comment by ShahriyarR** [comment]
As there is some unclear situations - will wait for Mykola's clarifications on this.

**Comment by ShahriyarR** [comment]
I have a quick call with @delgod 
Here are the notes:
* If no options provided it will take 40% of available RAM
* If -e METRICS_MEMORY -> it will multiply given value to 1024
* If --memory option provided then It will grab 40% from given value.

All over mentioned commands are valid.

**Comment by rnovikovP** [comment]
there also the link to Product requirement   https://confluence.percona.com/display/PMM/Memory+Auto+Configuration+-+Milestone+1#MemoryAutoConfiguration-Milestone1-Technicalimplementation

**Comment by ShahriyarR** [comment]
Tests are ready to use and README was updated to reflect recent changes.
The test branch is `bugfix_issue258`
