### ISSUE TITLE
Make it possible to pass options to pmm-framework.sh for MySQL startup

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#261]
Currently all options are hardcoded.
It is valuable to have some option where we can pass bunch of options for starting MySQL:
`--mysqld-startup-options="--innodb-buffer-pool-size=1G,--innodb-log-file-size=1G"` etc.

**Comment by rameshvs02** [comment]
```
$> bash.exe .\pmm-tests\pmm-framework.sh | grep.exe mysqld-startup-options
 --mysqld-startup-options         Pass MySQL startup options
$>
```
Issue fixed in pmm-test branch

**Comment by rameshvs02** [comment]
@ShahriyarR Please check https://github.com/Percona-QA/percona-qa/pull/263
