### ISSUE TITLE
BATS run failed with PS 5.7

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#98]
Seems to be it is due to new sysbench version.
```
WARN: Running stress tests; creating tables and inserting using sysbench
Using MYSQL_SOCK=/tmp/PS_NODE_1.sock
sysbench 1.0.6 (using bundled LuaJIT 2.1.0-beta2)

FATAL: unable to connect to MySQL server on socket '/tmp/PS_NODE_1.sock', aborting...
FATAL: error 1049: Unknown database 'test'
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:83: connection creation failed
Using MYSQL_SOCK=/tmp/PS_NODE_2.sock
sysbench 1.0.6 (using bundled LuaJIT 2.1.0-beta2)

FATAL: unable to connect to MySQL server on socket '/tmp/PS_NODE_2.sock', aborting...
FATAL: error 1049: Unknown database 'test'
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:83: connection creation failed
Using MYSQL_SOCK=/tmp/PS_NODE_3.sock
sysbench 1.0.6 (using bundled LuaJIT 2.1.0-beta2)

FATAL: unable to connect to MySQL server on socket '/tmp/PS_NODE_3.sock', aborting...
FATAL: error 1049: Unknown database 'test'
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:83: connection creation failed
```

**Comment by ShahriyarR** [comment]
Seems to be fixed:

```
WARN: Running stress tests; creating tables and inserting using sysbench
Using MYSQL_SOCK=/tmp/PS_NODE_1.sock
sysbench 1.0.6 (using bundled LuaJIT 2.1.0-beta2)

Creating table 'sbtest1'...
Inserting 100000 records into 'sbtest1'
Creating a secondary index on 'sbtest1'...
Using MYSQL_SOCK=/tmp/PS_NODE_2.sock
sysbench 1.0.6 (using bundled LuaJIT 2.1.0-beta2)

Creating table 'sbtest1'...
Inserting 100000 records into 'sbtest1'
Creating a secondary index on 'sbtest1'...
Using MYSQL_SOCK=/tmp/PS_NODE_3.sock
sysbench 1.0.6 (using bundled LuaJIT 2.1.0-beta2)

Creating table 'sbtest1'...
Inserting 100000 records into 'sbtest1'
Creating a secondary index on 'sbtest1'...
```

**Comment by woson-wang** [comment]
I faced the same issue, too. Could you tell me how to fix it? Thank you

sysbench --db-driver=mysql --mysql-host=192.168.100.101 --mysql-db=sbtest --mysql-user=test --mysql-password=123123 --table_size=10000 --tables=1 --threads=200 --time=900 --report-interval=10 /usr/share/sysbench/oltp_update_index.lua  prepare
[ERROR]
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:83: connection creation failed
FATAL: unable to connect to MySQL server on host '192.168.100.101 --mysql-db=sbtest', port 3306, aborting...
FATAL: error 2005: Unknown MySQL server host '192.168.100.101 --mysql-db=sbtest' (1)

Version:
sysbench 1.0.11 (using bundled LuaJIT 2.1.0-beta2)

**Comment by ShahriyarR** [comment]
Well according to the issue description for the problem was missing database while running sysbench.
For you it seems to be the host issue. Maybe it should be `--mysql-host='192.168.100.101'`

**Comment by woson-wang** [comment]
Hello, i tried ` sysbench /usr/share/sysbench/oltp_update_index.lua --db-driver=mysql --mysql-host='192.168.100.101' --mysql-db=sbtest --mysql-user=test --mysql-password=123123 --table_size=10000 --tables=1 --threads=200 --time=900 --report-interval=10 prepare`, and still got the same error messages.

My MySQL version is 5.7.20

**Comment by woson-wang** [comment]
I reinstall sysbench, and this time it works!!! Thank you^~^
